apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mario-game
  name: mario-game
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mario-game
  strategy: {}
  template:
    metadata:
      labels:
        app: mario-game
    spec:
      containers:
      - image: kaminskypavel/mario
        name: mario-game
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: mario-game-service
  labels:
    app: mario-game-service
spec:
  type: NodePort
  ports:
  - name: mario-game
    port: 8080
    nodePort: 30002
  selector:
    app: mario-game

